- name: Install custom facts in ansible nodes
  hosts: all

  tasks:
    - name: Create the ansible facts folder
      file: path=/etc/ansible/facts.d state=directory mode=0755

    - name: Install the custom fact
      copy: src=ip.fact dest=/etc/ansible/facts.d/ip.fact mode=700

