- name: This playbook will install nginx, configures the document root folder, deploys custom web page
  hosts: dev
  vars:
    - greeting_msg: Welcome to DevOps!
    - provisioner_tool: Docker
    - conf_mgr_tool: Ansible
  tasks:
    - name: Install nginx in Ubuntu
      apt: name=nginx state=latest update_cache=yes

    - name: Start the nginx service in Ubuntu
      shell: service nginx start

    - name: Create the custom document root folder
      file: path=/var/html state=directory mode=0755

    - name: Retrieve IP address of the ubuntu node
      shell: hostname -i
      register: output

    - debug: var=output

    - name: Deploy custom web page
      template: src=index.html.j2 dest=/var/html/index.html

    - name: Configure document root folder
      copy: src=default dest=/etc/nginx/sites-available/default

    # It is recommended to use service module for managing services, however due to a known bug in service module 
    # relate to containers, it won't start/restart the service. Hence we have no option other than using shell module.
    # But if the ansible node is not a container, consider using service module.
    - name: Restart nginx to apply config changes
      shell: service nginx restart

- name: This play will install nginx, configures document root fodler, deploys custom web page in CentOS ansible nodes
  hosts: qa
  tasks:
