---
- name: Configure Apache2 document root folder in Ubuntu 
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf
  notify:
    - Restart apache in Ubuntu

- name: Grant permission to our custom document root folder
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify:
    - Restart apache in Ubuntu
