- name: This playbook will install nginx, configures the document root folder, deploys custom web page
  hosts: all 

  tasks:
    - include: "install-nginx-{{ansible_distribution|lower}}.yml"
    - include: common-nginx-tasks.yml
    - include: "configure-nginx-{{ansible_distribution|lower}}.yml"

  # Dynamic includes aren't supported in handler, hence had to call out the name of handler ymls explicitly below.
  handlers:
    - include: start-nginx-ubuntu.yml
    - include: start-nginx-centos.yml
    - include: restart-nginx-ubuntu.yml
    - include: restart-nginx-centos.yml

