- name: This playbook will automate the custom ansible node image build process
  hosts: localhost
  tasks:
     - name: Cleanup all ubuntu containers
       shell: docker rm -f $(docker ps -aq --filter="name=ubuntu*")
       ignore_errors: yes
          
     - name: Remove the existing ansible ubuntu image
       shell: docker rmi tektutor/ansible-ubuntu:latest
       ignore_errors: yes

     - name: Build ubuntu ansible node image
       docker_image:
           name: tektutor/ansible-ubuntu:latest
           build:
             dockerfile: UbuntuDockerfile
             path: .
             pull: no
           state: present
           source: build
