- name: This playbook will automate the custom ansible node image build process
  hosts: localhost
  tasks:
     - name: Cleanup all ubuntu containers
       shell: docker rm -f $(docker ps -aq --filter="name=ubuntu*")
       ignore_errors: yes
          
     - name: Remove the existing ansible ubuntu image
       docker_image:
          name: tektutor/ansible-ubuntu:latest
          state: absent

     - name: Build ubuntu ansible node image
       docker_image:
           name: tektutor/ansible-ubuntu:latest
           build:
             dockerfile: UbuntuDockerfile
             path: .
             pull: no
           state: present
           source: build

     - name: Cleanup all centos containers
       shell: docker rm -f $(docker ps -aq --filter="name=centos*")
       ignore_errors: yes
          
     - name: Remove the existing ansible centos image
       docker_image:
          name: tektutor/ansible-centos:latest
          state: absent

     - name: Build centos ansible node image
       docker_image:
           name: tektutor/ansible-centos:latest
           build:
             dockerfile: CentOSDockerfile
             path: .
             pull: no
           state: present
           source: build

     - name: This is test task
       debug: msg="Test task"
       tags:
         - Test
